[build-system]
requires = [
    "setuptools>=45",
    "setuptools_scm[toml]",
    "setuptools_scm_git_archive"
]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
fallback_version = "0.0.0.dev0"
